config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :articles
  resources :categories
  resources :wikis do
    resources :articles
  end
  resources :snapshots
  resources :roles
  

  root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
  has_many :articles_category
  has_many :categories, through: :articles_category
  has_many :snapshots
  accepts_nested_attributes_for :snapshots

  validates :title, presence: true, length: {maximum: 20}

	

end

app/models/articles_category.rb
class ArticlesCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category

  validates :article, :category, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles_category
  has_many :articles, through: :articles_category

  validates :name, presence: true, length: {maximum: 30}
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  validates :user, :wiki, presence: true

end

app/models/snapshot.rb
class Snapshot < ActiveRecord::Base

  belongs_to :article
  belongs_to :user

  validates :body, presence: true
  # validates :article, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :snapshots
  has_many :roles
  has_many :wikis, through: :roles
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :roles
  has_many :users, through: :roles
  has_many :articles

  validates :name, presence: true, length: {maximum: 30}

  def administered_by?(user)
    self.roles.any? do |role|
      role.admin? && role.user_id == user.id
    end
  end

  def self.search(search)
  if search
  	where('title LIKE ?', "%#{search}%")
  else 
  	all
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private



  def is_admin?
    if current_user
      current_user.roles.any? { |role| role.admin? && role.wiki.administered_by?(current_user) }
    end
  end

  def ensure_admin!
    unless is_admin?
    @admin_errors = ["Insufficient permissions for the page you are trying to access"]

      # sign_out current_user

      # redirect_to root_path

      return false
    end
  end

end

# class AdminController < ApplicationController
  # before_action :ensure_admin!

# end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  before_action :ensure_admin!, only: [:edit, :update, :destroy]
  

 	def index
    @articles = Article.all
 	end

  def new
    	@article = Article.new
      @wiki = Wiki.find_by(id: params[:wiki_id])
      @article.snapshots << Snapshot.new

 	end

  	def create
      @wiki = Wiki.find(params[:wiki_id])
      @article = Article.new(article_params.merge(wiki: @wiki))
      if @article.save
        redirect_to wiki_path(@wiki)
      else
        render 'new'
      end
  	end

	def edit
    @article = Article.find(params[:id])

      render 'edit'
	end

	def show
    @article = Article.find(params[:id])
    @snapshot = Snapshot.find(@article.snapshots.last.id)
    @user = @snapshot.user
    @wiki = Wiki.find_by(id: @article.wiki_id)
		render 'show'
	end

	def update
    @article = Article.find(params[:id])
    @wiki = Wiki.find_by(id: @article.wiki_id)
      if @article.update(article_params)
        @snapshot = Snapshot.find(@article.snapshots.last.id)
        @snapshot.article = @article
          if @snapshot = Snapshot.new(snapshot_params)
             @snapshot.article = @article
            if @snapshot.save
              redirect_to article_path
            else
              render 'edit'
            end
          else
           render 'edit'
          end
      else
        render 'edit'
      end
	end

	def destroy
    @article = Article.find(params[:id])
    @wiki = Wiki.find_by(id: @article.wiki_id)
    @snapshot = Snapshot.find(@article.snapshots.last.id)
      @article.destroy

      @snapshot.destroy

      redirect_to wiki_path(@wiki)
	end

	private

	def article_params
      params.require(:article).permit(
        :title,
        snapshots_attributes: [:body]
      )
  end

  def snapshot_params
      params.require(:article).require(:snapshots).permit(:body)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, exception: [:index, :show]
  before_action :ensure_admin!, only: [:update, :edit, :destroy]


  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(name: params[:name])

    if @category.save
      redirect category_url(category)
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles

    render 'show'
  end

  def destroy
    Category.find(params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, exception: [:index, :show]
  before_action :ensure_admin!, only: [:update, :edit, :destroy]


	def index
		@groups = Group.all
	end

	def show
		@group = Group.find(params[:id])
	end

	def new
	end

	def edit
		@group = Group.find(params[:id])
	end

	def create
		@group = Group.new(params.require(:group).permit(:name))
		@group.save
  		redirect_to @group
	end

	def update
		 @group = Group.find(params[:id])

  		if @group.update(params.require(:group).permit(:name))
    		redirect_to @group
  		else
    		render 'edit'
  		end
	end

	def destroy
		@group = Group.find(params[:id])
  		@group.destroy

  		redirect_to groups_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @articles = Article.all
  end

  def search
    @wiki_query = Article.search do
      keywords(params[:title])
    end
    @products = @wiki_query.results
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!, exception: [:index, :show, :create]

	def index
		@wiki = Wiki.find_by(id: params[:format].to_i)
	end

	def create
		@wiki = Wiki.find_by(id: params[:wiki_id])
		@role = Role.create!(user_id: current_user.id, wiki_id: @wiki.id, admin?: false)
		redirect_to "/wikis/#{@wiki.id}"
	end

	def update
		@role = Role.find_by(id: params[:role_id])
		@roles = @role.wiki.roles
		@role.update(admin?: params[:admin?])
		redirect_to :back
	end

end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
	before_action :authenticate_user!	

	def show
		@snapshot = Snapshot.find(params[:id])
    	@article = Article.find(@snapshot.article_id)
		render 'show'
	end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :ensure_admin!, only: [:edit, :update, :destroy]

	def index
		@wikis = Wiki.all
	end

	def show
		@wiki = Wiki.find(params[:id])
		@wikis = Wiki.search(params[:search])
		@role = @wiki.roles.new
	end

	def edit
		@wiki = Wiki.find(params[:id])
	end

	def create
		@wiki = Wiki.new(params.require(:wiki).permit(:name))
    	@wiki.save
    	@wiki.roles.create(admin?: true, user_id: current_user.id, wiki_id: @wiki.id)
      	redirect_to @wiki
	end

	def update
		 @wiki = Wiki.find(params[:id])

  		if @wiki.update(params.require(:wiki).permit(:name))
    		redirect_to @wiki
  		else
    		render 'edit'
  		end
	end

	def destroy
		@wiki = Wiki.find(params[:id])
  		@wiki.destroy

  		redirect_to wikis_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper


end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/articles/_article_form.html.erb
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "input-field" %>
  </p>
 
  <p>
  <%= f.fields_for :snapshots do |s| %>
    <%= s.label :body %><br>
    <%= s.cktext_area :body, rows: 10, class: "input-field" %>
    <% end %>
  </p>
 
  <p>
    <%= f.submit "submit", class: "button" %>
  </p>

app/views/articles/edit.html.erb
<div class ="container">

<h2>edit your article</h2>

<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "input-field" %>
  </p>
    <%= f.fields_for :snapshots do |s| %>
    <%= s.label :body %><br>
    <%= s.cktext_area :body, class: "input-field", rows: 10, value: @article.snapshots.last.body%>
    <% end %>
  </p>
  <p>
    <%= f.submit "submit", class: "button" %>
  </p>
 
<% end %>
</div>

app/views/articles/index.html.erb
<div class ="container">

  <h2>Welcome to the Articles Index!</h2>


  <% @articles.each do |article| %>
  <h4>Title:</h4> <%= article.title %><br>
  <h4>Body:</h4> 
  <% unless article.snapshots.empty? %>
  <%= article.snapshots.last.body.html_safe%><br>
  <%= link_to 'Show', article_path(article) %>
  <%= link_to 'Edit', edit_article_path(article) %>
  <%= link_to 'Destroy', article_path(article), method: "delete" %>
  <% end %>
  <% end %>
  <p>
  	Create a <a href='articles/new'>new</a> article!
  </p>

</div>

app/views/articles/new.html.erb
<div class ="container">

  <h2 class="title-for-line">create an article for your wiki</h2>

  <%= form_for [@wiki, @article] do |f| %>

  <%= render 'article_form', f: f %>

  <% end %>

</div>

app/views/articles/search.html.erb
<!-- 
.results
  - @search.each_hit_with_result do |hit, post|
    .result
      %h2= h post.title
      %h6== (#{h hit.score})
      %p= h truncate(post.body, :length => 100)
.pagination
  = will_paginate(@search.results) -->


<div class='results'>
	<% @search.each_hit_with_result do |hit, post| %>
		<div class='result'>
			<h2><%= post.title %></h2>
			<h6><%= #{hit.score}%></h6>
			<p> <%= truncate(post.body, length: 100)%></p>
		</div>
		</div class ='pagination'>
			<% will_paginate(@search.results) %>
		</div>
	<% end %>
</div>

app/views/articles/show.html.erb
<div class ="container">

  <h3 class="title-for-line">Wiki: <%= @wiki.name %> </h3>
  <h4 id="article-title">Article: <%= @article.title %></h4>
          <% @article.categories.each do |category| %>
            <div id="category">filed under: <%= category.name %></div>
            <% end %>

    <div><%= @snapshot.body.html_safe %></div>

    <% if current_user && @wiki.administered_by?(current_user) %>

      <div class="article-show-bottom-links"><%= link_to 'see your revisions history!', snapshot_path(@snapshot) %> • <%= link_to 'edit your article', edit_article_path(@article) %> • <%= link_to 'delete your article', article_path(@article), method: "delete" %></div><br>


    <% end %>

</div>

app/views/categories/index.html.erb
<div class ="container">

  <h2>categories</h2>

  <% @categories.each do |category| %>
    <div><%= link_to category.name, category_path %></div>
  <% end %>
  
</div>

app/views/categories/new.html.erb
<div class ="container">

  <h2>create a new category</h2>
  <%= form_for :category, url: {action: "create"} do |f| %>
    <span>Wiki Name: </span>
    <%= f.text_field :name, class: "form-field" %>
    <%= f.submit "submit" %>
  <% end %>

</div>

app/views/categories/show.html.erb
<div class ="container">

  <% @articles.each do |article| %>
    <%= link_to article.title, article_path(article) %>
  <% end %>

</div>

app/views/home/index.html.erb
<!-- <h4>this is a wiki all about ruby on rails! create a wiki or read about anything rails-related here</h4>
 -->

<div class ="container">

  <% if user_signed_in? %>

    <div id="browse-wikis"><%= link_to "browse our wikis!", wikis_path%> • <%= link_to "create your own wiki today!", new_wiki_path %></div>

  <% else %>

   <div id="browse-wikis"><%= link_to "browse our wikis!", wikis_path%></div>

    <div id="login-home-section"><%= link_to "Log in", new_user_session_path %> or <%= link_to "sign up to create a rails wiki today!", new_user_registration_path %></div>
    
  <% end %>


    <h4 id="featured-articles-homepage-title">featured articles:</h4>
    
      <% @articles.each do |article| %>
      <% if article.featured? %>
        <h3><%= link_to article.title, article_path(article), class: "homepage-article-title" %></h3>
          <% article.categories.each do |category| %>
            <div id="category">filed under: <%= category.name %></div>
            <% end %>
      <% end %>

    <% end %> 

</div>

app/views/roles/index.html.erb
<div class="container">
  <h1> Edit Admin Roles </h1>
  <ul>
    <% @wiki.roles.each do |role| %>
      <li>
        <%= form_tag("/roles/#{role.id}", method: :put, class:"role-form") %>
          <%= hidden_field_tag :role_id, role.id %>
          <% if @wiki.administered_by?(role.user) %>
            <%= hidden_field_tag :admin?, false %>
            <%=check_box_tag(:admin?, true, checked = true)%>
          <% else %>
            <%= hidden_field_tag :admin?, false %>
            <%=check_box_tag(:admin?, true) %>
          <% end %>
        <%= submit_tag "", style: "display:none;" %>
        <%= role.user.email %>
      </li>
    <% end %>
  </ul>
  <div class="button roll-submit" style="width:10%;">Submit</div>
</div>

app/views/snapshots/show.html.erb
<div class ="container">

  <h2 class="title-for-line">your article revision history</h2>
  
  <% @article.snapshots.each do |snapshot| %>
    <%= snapshot.body.html_safe %><br><br>
    <b>Created:</b> <%= snapshot.created_at %><br>
    <b>Updated:</b> <%= snapshot.updated_at %><br><br>
  <% end %>

  <div class="back-link">back to your <%= link_to 'article', article_path(@article) %>!</div>

</div>

app/views/wikis/edit.html.erb
<div class ="container">

  <h2 class="title-for-line">edit your wiki</h2>

  <%= form_for :wiki, url: wiki_path(@wiki), method: :patch do |f| %>

    <% if @wiki.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@wiki.errors.count, "error") %> prohibited
          this wiki from being saved:
        </h2>
        <ul>
          <% @wiki.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "input-field" %>
    </p>
    <p>
      <%= f.submit "submit", class: "button" %>

    </p>

  <% end %>

  <%= link_to 'Back', wikis_path %>

</div>

app/views/wikis/index.html.erb
<div class ="container">

  <h2 class="title-for-line">wikirailsopedia wikis:</h2>

    
    <% @wikis.each do |wiki| %>
      <div class="wiki-name"><h3><%= link_to wiki.name, wiki_path(wiki) %></h3></div>

        <% if current_user && wiki.administered_by?(current_user) %>
      <div><%= link_to 'edit this wiki', edit_wiki_path(wiki) %> • <%= link_to 'delete this wiki', wiki_path(wiki), method: :delete, data: { confirm: 'Are you sure?' } %></div>
      


        <% end %>
    <% end %>
    <div class="create-new-wiki-link"><%= link_to "don't see a wiki you like? create a new wiki!", new_wiki_path %></div>

</div>

app/views/wikis/new.html.erb
<div class ="container">


  <h2 class="title-for-line">create a new wiki:</h2>

  <%= form_for :wiki, url: wikis_path do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "input-field" %>
    <p>
      <%= f.submit "submit", class: "button" %>
    </p>
  <% end %>

</div>

app/views/wikis/show.html.erb
<div class ="container">

  <div><h2 class="title-for-line"><%= @wiki.name %> Wiki</h2></div>

  <h3>Articles:</h3>
  <% if @wiki.articles.empty?  %>
    <div>there are currently no articles in this wiki, check back soon!</div>
  <% else %> 
  <ul>
    <% @wiki.articles.each do |article| %>
      <li><%= link_to article.title, article_path(article) %></li>
    <%end%>
    </ul>

  <% end %>

  <% if current_user && @wiki.administered_by?(current_user) %>
  <div><h3><%= link_to "create a new article for this wiki", new_article_path %></div></h3><br>
  <% end %>


  <h4>Search for an article within this wiki:</h4>

  <%= form_tag wikis_path, :method => 'get' do %>
  <p>
  <%= text_field_tag :search, params[:search], class: "input-field" %>
  <%= submit_tag "search", :name => nil, class: "button" %>
  </p>
  <% end %>

  <% if current_user && !@wiki.administered_by?(current_user) %>
  <p>would you like to add an article to this wiki?</p>
  <%= form_tag '/roles' do %>
    <%= hidden_field_tag(:wiki_id, @wiki.id)%>
    <%= submit_tag "join this wiki", name: 'join_wiki', class: "button" %>
  <% end %>
  <% end %>

  <% if current_user && @wiki.administered_by?(current_user) %>
  <div><%= link_to "edit this wiki", edit_wiki_path(@wiki) %> • <%= link_to 'delete this wiki', wiki_path(@wiki), method: :delete, data: { confirm: 'Are you sure?' } %>  • <%= link_to 'manage wiki user roles', roles_path(@wiki) %> </div> 
  <% end %>

  <div class="back-link"><%= link_to 'back', wikis_path %></div>

</div>